bluehouseapp_api_node_index:
    path:     /node
    methods: [GET]
    defaults:
      _controller: bluehouseapp.controller.node:indexAction
      _bluehouseapp:
        sortable: true
        sorting:
            no:  desc
        filterable: true
        criteria:
          status: true
          enabled: true

bluehouseapp_api_node_show:
    path:     /node/show/{nodeCode}
    methods: [GET]
    defaults:
      _controller: bluehouseapp.controller.node:showAction
      _bluehouseapp:
        sortable: true
        sorting:
            no:  desc
        filterable: true
        criteria:
          status: true
          enabled: true
          code: [$nodeCode]

bluehouseapp_api_member_show:
    path:     /member/show/{username}
    defaults:
      _controller: bluehouseapp.controller.member:showAction
      _bluehouseapp:
        filterable: true
        criteria:
          locked: false
          enabled: true
          expired: false
          username: [$username]
    requirements: { _method: get }

bluehouseapp_api_member_post_index:
        path:    /member/posts/{memberId}
        defaults:
          _controller: bluehouseapp.controller.post:indexAction
          _bluehouseapp:
                sortable: true
                sorting:
                    modified:  desc
                filterable: true
                criteria:
                  status: true
                  enabled: true
                  member: [$memberId]
        requirements: { _method: get }

bluehouseapp_api_member_postCommment_index:
        path:    /member/postComments/{memberId}
        defaults:
          _controller: bluehouseapp.controller.postComment:indexAction
          _bluehouseapp:
                sortable: true
                sorting:
                    modified:  desc
                filterable: true
                criteria:
                  status: true
                  enabled: true
                  member: [$memberId]
        requirements: { _method: get }

bluehouseapp_api_node_post_index:
    path:     /node/posts/{nodeId}
    methods: [GET]
    defaults:
      _controller: bluehouseapp.controller.post:indexAction
      _bluehouseapp:
        sortable: true
        sorting:
            modified:  desc
        filterable: true
        criteria:
          status: true
          enabled: true
          node: [$nodeId]

bluehouseapp_api_post_index:
    path: /post
    methods: [GET]
    defaults:
      _controller: bluehouseapp.controller.post:indexAction
      _bluehouseapp:
        sortable: true
        sorting:
            modified:  desc
        filterable: true
        criteria:
          status: true
          enabled: true

bluehouseapp_api_post_show:
        path:    /post/show/{id}
        methods: [GET]
        defaults:
          _controller: bluehouseapp.controller.post:showAction
          _bluehouseapp:
                sortable: true
                sorting:
                    modified:  desc
                filterable: true
                criteria:
                  status: true
                  enabled: true






bluehouseapp_api_post_postComments_index:
    path:     /post/postComments/{postId}
    methods: [GET]
    defaults:
      _controller: bluehouseapp.controller.postComment:indexAction
      _bluehouseapp:
        sortable: true
        sorting:
            modified:  desc
        filterable: true
        criteria:
          status: true
          enabled: true
          post: [$postId]