Bluehouseapp\Bundle\CoreBundle\Entity\Node:
    exclusion_policy: ALL
    xml_root_name: node
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        name:
            expose: true
            type: string
        description:
             expose: true
             type: string
        nodeimageurl:
             expose: true
             type: string
    relations:
        - rel: posts
          href:
                route: bluehouseapp_api_node_post_index
                parameters:
                    nodeId: expr(object.getId())
