Bluehouseapp\Bundle\CoreBundle\Entity\Member:
    exclusion_policy: ALL
    xml_root_name: member
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        nickname:
            expose: true
            type: string
        username:
            expose: true
            type: string
        oschina:
            expose: true
            type: string
        weibo:
            expose: true
            type: string
        city:
            expose: true
            type: string
        website:
            expose: true
            type: string
        description:
            expose: true
            type: string
        userimageurl:
            expose: true
            type: string
    relations:
        - rel: posts
          href:
                route: bluehouseapp_api_member_post_index
                parameters:
                    memberId: expr(object.getId())
        - rel: postComments
          href:
                route: bluehouseapp_api_member_postCommment_index
                parameters:
                    memberId: expr(object.getId())
