Bluehouseapp\Bundle\CoreBundle\Entity\Post:
    exclusion_policy: ALL
    xml_root_name: post
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        title:
            expose: true
            type: string
        content:
            expose: true
            type: string
        lastCommentTime:
            expose: true
            type: DateTime
        created:
            expose: true
            type: DateTime
        modified:
            expose: true
            type: DateTime
        commentCount:
            expose: true
            type: integer
    virtual_properties:
        getMemberName:
            serialized_name: memberName
            type: string
        getNodeName:
            serialized_name: nodeName
            type: string
        getMemberImageURL:
            serialized_name: memberimageurl
            type: string
    relations:
        - rel: detail
          href:
                route: bluehouseapp_api_post_show
                parameters:
                    id: expr(object.getId())
        - rel: node
          href:
                route: bluehouseapp_api_node_show
                parameters:
                    nodeCode: expr(object.getNode().getCode())
        - rel: member
          href:
                route: bluehouseapp_api_member_show
                parameters:
                    username: expr(object.getMember().getUserName())
        - rel: postComments
          href:
                route: bluehouseapp_api_post_postComments_index
                parameters:
                    postId: expr(object.getId())





