bluehouseapp_node_index:
    path:     /
    defaults:
      _controller: bluehouseapp.controller.node:indexAction
      _bluehouseapp:
        sortable: true
        sorting:
            id:  desc
        filterable: true
        criteria:
          status: true

bluehouseapp_node_show:
    path:     /{id}/show
    defaults: { _controller: "bluehouseapp.controller.node:showAction" }

bluehouseapp_node_new:
    path:     /new
    defaults: { _controller: "bluehouseapp.controller.node:createAction" }

bluehouseapp_node_create:
    path:     /create
    defaults: { _controller: "bluehouseapp.controller.node:createAction" }
    requirements: { _method: post }

bluehouseapp_node_edit:
    path:     /{id}/edit
    defaults: { _controller: "bluehouseapp.controller.node:updateAction" }

bluehouseapp_node_update:
    path:     /{id}/update
    defaults: { _controller: "bluehouseapp.controller.node:updateAction" }
    requirements: { _method: post|put }

bluehouseapp_node_delete:
    path:     /{id}/delete
    defaults: { _controller: "bluehouseapp.controller.node:deleteAction" }
    requirements: { _method: get|post|delete }

bluehouseapp_node_enable:
    path:     /enable/{id}
    defaults: { _controller: "bluehouseapp.controller.node:enableAction" }
    requirements: { _method: get|post }
bluehouseapp_node_disable:
    path:     /disable/{id}
    defaults: { _controller: "bluehouseapp.controller.node:disableAction" }
    requirements: { _method: get|post }