<?php

namespace Blackhouseapp\Bundle\BluehouseappBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BanedIPsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanedIPsRepository extends EntityRepository
{
}
