welcome:
    path:     /
    defaults: { _controller: "BluehouseappWebBundle:Welcome:index" }
    requirements: { _method: get }

bluehouse_backend:
        resource: "@BluehouseappWebBundle/Resources/config/routing/backend/main.yml"
        prefix: /web
bluehouse_frontend:
        resource: "@BluehouseappWebBundle/Resources/config/routing/frontend/main.yml"
        prefix: /web